# serverless.yml

service: proozl

provider:
    name: aws
    runtime: python3.8
    stage: 'dev'
    region: 'us-east-2'
    role: arn:aws:iam::555989344246:role/proozl-role

package:
    exclude:
        - test/**
        - playground/**
        - layers/**
    
layers:
    lib:
        path: layers/proozl-dep/
        name: 'proozl-dep'
        description:  Dependencies needed for proozl
        compatibleRuntimes:
            - python3.8
            - python3.7
        retain: true


functions:
    arxiv-result:
        handler: lambdas/arxiv_result/lambda_function.lambda_handler
        layers:
            - { Ref: LibLambdaLayer }
        timeout: 180
    proozl-analyze:
        handler: lambdas/proozl_analyze/lambda_function.lambda_handler
        layers:
            - { Ref: LibLambdaLayer }
        timeout: 120
    result-update: 
        handler: lambdas/result_update/lambda_function.lambda_handler
        layers:
            - { Ref: LibLambdaLayer }
        timeout: 300

plugins:
    - serverless-plugin-layer-manager
