# serverless.yml

service: proozl

provider:
    name: aws
    runtime: python3.8
    stage: 'dev'
    region: 'us-east-2'

package:
    exclude:
        - test/**
        - playground/**
        - layers/**
    
layers:
    lib:
        path: layers/proozl-dep/
        name: 'proozl-dep'
        description:  Dependencies needed for proozl
        compatibleRuntimes:
            - python3.8
            - python3.7
        retain: true

functions:
    arxiv-result:
        role: arn:aws:iam::555989344246:role/proozl-role
        handler: lambdas/arxiv_result/lambda_function.lambda_handler
        layers:
            - { Ref: LibLambdaLayer }

plugins:
    - serverless-plugin-layer-manager
